# Site settings
title: 卡尔的咖啡厅
email: david@mail.bnu.edu.cn
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://lgm.name" # the base hostname & protocol for your site
twitter_username: cmldyu
github_username:  cmldyu

# Build settings
markdown: kramdown

paginate: 4

author: 洛光明

gems: [jekyll-paginate]
